### ISSUE TITLE
#INC-5312: Missing image

### ISSUE THREAD

**Issue by vanessa-cooper** [ObelusFamily/Anythink-Market-e1jwz#3]
Cool! Now, It seems that when creating a new product without an image, there are broken images showing up in the product catalog. Please fix this by replicating this bug locally with mock data.
Take a screenshot of the fix and attach it to a PR when you close the bug. There's a placeholder image in the repo that you can use named `placeholder.png`

**Comment by Nirajsah** [comment]
<img width="1205" alt="Screenshot 2022-08-02 at 2 33 58 PM" src="https://user-images.githubusercontent.com/51414373/182342189-425f3458-2cbe-413b-933f-2b833a60c1d5.png">


placeholder.png added as a default mock data if any image is not present
